### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ghost** [fletchroast/prj-rev-bwfs-dasmoto#6]
Satisfactory 👍 

Great job reproducing the web page according to the design mock. You've written some very organized and efficient HTML & CSS as well, good job!

See if you can come back to this project when you've learned a little more about semantic markup, and see if you can improve your code by adding semantic tags instead of `div`s. You should also feel free to expand on this project and maybe add a navigation section.

**Comment by fletchroast** [comment]
Hi Steve,

Thanks for reviewing this project so late and thanks for your feedback, all taken on board!

Could you give me an example of a semantic tag you would use instead of a <div> ? 

I will come back to this project after I have caught up with the syllabus - no doubt it will be a breeze by then! Thanks,

Callum

**Comment by fletchroast** [comment]
erm.. instead of a div*

**Comment by fletchroast** [comment]
Found my answer here: https://github.com/Jasminejf/prj-rev-bwfs-tea-cozy/issues/1

Cheers Steve!
